#!/usr/bin/with-contenv bash

nastools_update

if [ "${NASTOOL_VERSION}" = "lite" ]; then
    mkdir -p /.pm2
    chown -R "${PUID}":"${PGID}" "${WORKDIR}" /config /.pm2
else
    mkdir -p /.local
    mkdir -p /.pm2
    chown -R "${PUID}":"${PGID}" "${WORKDIR}" /config /usr/lib/chromium /.local /.pm2
    export PATH=${PATH}:/usr/lib/chromium
fi
