#!/usr/bin/with-contenv bash

if [ ! -f "/etc/nginx/http.d/default.conf" ]; then
	touch /etc/nginx/http.d/default.conf
else
    rm -rf /etc/nginx/http.d/default.conf
    touch /etc/nginx/http.d/default.conf
fi
cat > "/etc/nginx/http.d/default.conf" << EOF
server {
    listen 3080 default_server;
    server_name _;
    autoindex on;
    charset utf-8;
    location ${API_ROOT} {
        proxy_pass http://127.0.0.1:8088;
    }
    location / {
        proxy_pass http://127.0.0.1:3000;
        keepalive_timeout 6000s;
        proxy_read_timeout 6000s;
    }
}

EOF
